# Generated by Django 4.0.4 on 2022-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.TextField()),
                ('singer', models.TextField()),
                ('location', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
