# Generated by Django 4.0.4 on 2022-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.TextField()),
                ('singer', models.TextField()),
                ('location', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
